"use strict";
const $=id=>document.getElementById(id), ST=["FOR","DEX","CON","INT","SAG","CHA"], DEF=[15,14,13,12,10,8], wait=ms=>new Promise(r=>setTimeout(r,ms));
const baseNpc=(name,temp)=>({name,temp,patience:3,respect:0,warmth:0,hostility:0,discomfort:0});
let G={scene:"gate",char:null,mission:"offered",dassom:"neutral",focus:"kayla",topic:"mission",debug:false,inventory:[],clueSmoke:false,berriesKnown:false,artUnlocked:{},npcs:{kayla:baseNpc("Kayla","brute_mature"),hilam:baseNpc("Hilam","calm")} };
const norm=s=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replaceAll("’","'");
const any=(t,a)=>a.some(x=>t.includes(x)), mod=n=>Math.floor((n-10)/2), sign=n=>n>=0?`+${n}`:`${n}`;
function msg(c,h){let d=document.createElement("div");d.className="msg "+c;d.innerHTML=h;$("log").appendChild(d);$("log").scrollTop=$("log").scrollHeight}
function rel(n){let x=n.respect+n.warmth-n.hostility*3-n.discomfort;if(x<=-4)return"hostile";if(x<=-2)return"agacé";if(x>=3)return"favorable";if(x>=1)return"cordial";return"neutre"}
function side(){$("journal").innerHTML=`Mission du Lac Rose : ${G.mission==="active"?"acceptée":G.mission==="cancelled"?"annulée":"proposée"}<br>Statut à Dassom : ${G.dassom}`;$("inventory").textContent=G.inventory.join(", ")||"—";$("relations").innerHTML=Object.values(G.npcs).map(n=>`<div class=rel><span>${n.name}</span><span class="${["hostile","agacé"].includes(rel(n))?"bad":rel(n)==="favorable"?"good":""}">${rel(n)}</span></div>`).join("")}
const scenes={gate:["Entrée Nord de Dassom","🏰　👩‍🦳　🧑　⚔️"],outside:["Aux abords de Dassom","🏰　🚪　🌾　🛤️"],forest:["Bois Tendre","🌲　🌿　🌳　🍃"],clearing:["Clairière du Bois Tendre","🌲　🫐　🌿　🍒　🌳"],cabin:["Cabane du vieux fermier","🌲　🏚️　🔥　🐴　🌾"]};
function scene(s,illustrated=false){G.scene=s;let x=scenes[s];$("place").textContent=x[0];$("sceneArt").textContent=x[1];$("sceneArt").className="sceneArt"+(illustrated?" illustrated":"")}
function rewardArt(key,sceneName,text){if(!G.artUnlocked[key]){G.artUnlocked[key]=true;$("reward").hidden=false;scene(sceneName,true);setTimeout(()=>$("reward").hidden=true,3500)}msg("narrator",text)}
function target(t){if(any(t,["hilam","jumeau","garcon"]))return"hilam";if(any(t,["kayla","jumelle","fille","belle"]))return"kayla";return G.focus}
function social(t){if(any(t,["j'attaque","je frappe","je degaine","je lance un sort sur"]))return"attack";if(any(t,["je vais te tuer","je te defonce","menace"]))return"threat";if(any(t,["connasse","conasse","salope","idiote","idiot","cretin","cretine","petit con","ta gueule","je t'emmerde"]))return"insult";if(any(t,["je t\'aime","je vous aime","epouse moi","epouser","m\'epouser","marier","marie moi","veux-tu m\'epouser","veux tu m\'epouser","embrasse moi","amoureux","amoureuse"]))return"heavy";if(any(t,["belle","beau","magnifique","jolie","charmante"]))return"compliment";if(any(t,["pardon","desole","je m'excuse"]))return"apology";return"neutral"}
function topic(t){
 if(any(t,["qui etes-vous","qui etes vous","qui es-tu","qui es tu","votre nom","ton nom","presentez-vous","presente toi"]))return"identity";
 if((t.includes("pourquoi")||t.includes("a quoi"))&&any(t,["ramener","jumeaux","important","proteger","protecteur"]))return"importance";
 if((t.includes("pourquoi")||t.includes("comment ca se fait"))&&any(t,["nous","moi","choisi","recommande"]))return"selection";
 if(any(t,["on y gagne quoi","qu'est-ce qu'on gagne","qu'est ce qu'on gagne","recompense","recompenses","combien vous payez","combien ca rapporte","combien ça rapporte","paye combien","paiement","remunere"]))return"reward";
 if(any(t,["que puis-je faire","que dois-je faire","on doit faire quoi","quoi faire","objectif","quelle mission","c'est quoi la mission","c est quoi la mission"]))return"mission";
 if(any(t,["cachez","cache quelque","mentez","sincere"]))return"secret";
 if(any(t,["je refuse","pas envie","je ne veux pas","non merci"]))return"refusal";
 if(any(t,["allons-y","allons y","on y va","partons","je pars","je suis pret","je suis prête","nous sommes prets","nous sommes prêts","direction le bois","direction bois tendre","nous allons au bois","je vais au bois tendre"]))return"leave";
 if(/^(ok|okay|d'accord|daccord|tres bien|très bien|entendu|ca marche|ça marche|compris|bien)[.! ]*$/.test(t.trim()))return"ack";
 return null;
}
function observeIntent(t){return any(t,["qu\'est-ce que je vois","qu\'est ce que je vois","que vois-je","que vois je","est-ce que je vois","est ce que je vois","je vois quelque chose","j\'observe","je regarde autour","je regarde les alentours","observer les alentours","inspecte les alentours","a quoi ressemble","décris les lieux","decris les lieux"])}
function analyze(raw){let t=norm(raw),a={t,target:target(t),social:social(t),topic:topic(t),observe:observeIntent(t),question:raw.includes("?")||any(t,["pourquoi","quoi","comment","qui ","est-ce"])};if(G.debug){$("debug").hidden=false;$("debug").textContent=`cible=${a.target} | social=${a.social} | sujet=${a.topic} | observation=${a.observe} | scène=${G.scene}`}return a}
async function roll(label,ability,dc){let b=mod(G.char.stats[ability]),o=$("dice"),d=$("d20");$("dtitle").textContent=`${label} • ${ability} ${sign(b)}`;$("dcalc").textContent="";$("dresult").textContent="";o.classList.add("on");d.classList.add("roll");let spin=setInterval(()=>d.textContent=1+Math.floor(Math.random()*20),80);await wait(1800);clearInterval(spin);let raw=1+Math.floor(Math.random()*20),total=raw+b;d.classList.remove("roll");d.textContent=raw;await wait(700);$("dcalc").textContent=`${raw} ${sign(b)} = ${total} • DD ${dc}`;await wait(900);let ok=total>=dc;$("dresult").textContent=ok?"RÉUSSITE":"ÉCHEC";await wait(3000);o.classList.remove("on");return ok}
function socialGate(a){let n=G.npcs[a.target];G.focus=a.target;if(a.social==="attack"){G.npcs.kayla.hostility=5;G.npcs.hilam.hostility=5;G.mission="cancelled";G.dassom="expulsé";msg("narrator",`Tu attaques ${n.name}. Kayla et Hilam réagissent immédiatement : s'en prendre à l'un revient à se mettre les deux à dos.`);msg("npc","<b>Kayla :</b> « Mauvaise idée. Très mauvaise idée. »");msg("narrator","L'écart de puissance ne laisse aucune issue réaliste. Tu es repoussé puis escorté hors de Dassom.");scene("outside");side();return true}if(a.social==="insult"){n.hostility++;n.respect-=2;n.patience--;msg("npc",n.name==="Kayla"?(n.patience>1?"<b>Kayla :</b> « Je vais faire comme si j'avais mal entendu. Une fois. »":"<b>Kayla :</b> « Écoute, petit con, tu commences sérieusement à me fatiguer. »"):"<b>Hilam :</b> « Charmant. Tu veux recommencer avec un vocabulaire d'adulte ? »");return true}if(a.social==="heavy"){n.discomfort+=2;n.patience--;if(n.name==="Kayla"){msg("npc",n.discomfort<=2?"<b>Kayla :</b> « Doucement. On se connaît depuis trente secondes. On va rester sur la mission. »":n.discomfort<=4?"<b>Kayla :</b> « Non. Et là, tu commences à devenir lourd. »":"<b>Kayla :</b> « J\'ai dit non. Maintenant tu arrêtes. »")}else{msg("npc",n.discomfort<=2?"<b>Hilam :</b> « ...On peut revenir au Lac Rose, peut-être ? »":"<b>Hilam :</b> « Tu insistes vraiment ? Arrête. »")}return true}if(a.social==="compliment"){n.warmth++;msg("npc",`<b>${n.name} :</b> « Merci. »`);return true}if(a.social==="apology"){n.hostility=Math.max(0,n.hostility-1);n.discomfort=Math.max(0,n.discomfort-1);n.patience=Math.min(3,n.patience+1);msg("npc",`<b>${n.name} :</b> « Très bien. On repart de là. »`);return true}return false}
async function gate(a){
 if(socialGate(a))return;
 if(a.topic)G.topic=a.topic;
 if(a.topic==="identity"){msg("npc",a.target==="kayla"?"<b>Kayla :</b> « Kayla. Jumelle, et je règne actuellement sur Dassom avec Hilam. »":"<b>Hilam :</b> « Hilam. Jumeau de Kayla, et nous dirigeons Dassom ensemble. »");return}
 if(a.topic==="importance"){msg("narrator","Kayla marque un bref silence, presque gênée que la réponse lui paraisse aussi évidente.");msg("npc","<b>Kayla :</b> « Parce qu'ils sont les prochains dirigeants de Dassom et, accessoirement, des protecteurs d'Hackénia... »");return}
 if(a.topic==="selection"){msg("npc","<b>Hilam :</b> « Vous avez été recommandés par des personnes de vos entourages respectifs, des gens qui ont participé avec nous il y a des années de cela maintenant. »");return}
 if(a.topic==="reward"){msg("npc","<b>Kayla :</b> « Vous serez grassement récompensés. Dassom ne vous demandera pas de ramener ses futurs dirigeants pour une poignée de pièces. »");return}
 if(a.topic==="mission"){msg("npc","<b>Kayla :</b> « Traversez le Bois Tendre, rejoignez la chaîne de montagnes et trouvez l'entrée de la grotte menant au Lac Rose. Les nouveaux jumeaux devraient y apparaître. Ramenez-les à Dassom en sécurité. »");return}
 if(a.topic==="secret"){let ok=await roll("Perspicacité","SAG",12);msg("narrator",ok?"Kayla est sincère, mais un bref regard vers Hilam te confirme qu'ils ne disent pas tout.":"Son expression reste trop maîtrisée pour que tu puisses en tirer une certitude.");return}
 if(a.topic==="refusal"){G.mission="cancelled";msg("npc","<b>Kayla :</b> « Très bien. Nous trouverons quelqu'un d'autre. »");return}
 if(a.topic==="ack"){msg("npc",G.focus==="hilam"?"<b>Hilam :</b> « Bien. »":"<b>Kayla :</b> « Bien. »");return}
 if(a.topic==="leave"){if(G.mission!=="cancelled")G.mission="active";scene("forest");msg("narrator","Tu quittes Dassom et t'engages dans le Bois Tendre. Neria t'accompagne.");return}
 if(a.question){msg("npc",`<b>${G.npcs[a.target].name} :</b> « Je ne suis pas certaine d'avoir compris ta question. Reformule-la. »`);return}
 msg("npc",G.focus==="hilam"?"<b>Hilam :</b> « D'accord. »":"<b>Kayla :</b> « D'accord. »");
}
async function forest(a){if(a.observe){rewardArt("clearing","clearing","En prenant réellement le temps de regarder autour de toi, tu repères une petite clairière bordée de nombreux arbres. Plusieurs buissons chargés de baies noires, bleues et rouges poussent à sa lisière.");return}if(any(a.t,["fumee","trace","cherche quelque chose","fouille"])){let ok=await roll("Perception","SAG",11);if(ok){G.clueSmoke=true;msg("narrator","Au-delà de la clairière, une fine fumée se détache entre les branches, assez loin sur le côté du chemin.")}else msg("narrator","Tu scrutes les alentours mais rien d'inhabituel ne te saute aux yeux.");return}if(any(a.t,["separe","seul","m'eloigne du groupe"])){let ok=await roll("Perception","SAG",11);msg("narrator",ok?"Un grognement te prévient : un loup affamé rôde tout près. Tu n'es pas surpris.":"Un loup affamé surgit des fourrés et te surprend.");return}if(any(a.t,["avance","continue","clairiere"])){scene("clearing");msg("narrator","Tu poursuis jusqu'à une petite clairière bordée d'arbres et de buissons fruitiers.");return}msg("system","Tu peux explorer librement : observer, chercher des traces, t'éloigner du groupe ou poursuivre la route.")}
async function clearing(a){if(a.observe||any(a.t,["baie","buisson","fruit"])){rewardArt("berries","clearing","Tu examines mieux la clairière : trois sortes de baies ressortent nettement, noires, bleues et rouges.");if(any(a.t,["propriete","identifier","reconnaitre","connaitre","nature"])){let ok=await roll("Nature","INT",11);if(ok){G.berriesKnown=true;msg("narrator","Tu identifies leurs propriétés : noire contre la putréfaction ; bleue rend 1d4−1 PV ; rouge retire 1d4 PV chaque heure pendant sa digestion, durant 6 h.")}else msg("narrator","Tu n'es pas assez certain de leur nature pour t'y fier.");}return}if(any(a.t,["cueille","recolte","prends"])&&any(a.t,["noire","bleue","rouge"])){let c=a.t.includes("rouge")?"rouge":a.t.includes("bleue")?"bleue":"noire";G.inventory.push("baie "+c);msg("narrator",`Tu récoltes une baie ${c}.`);return}if(any(a.t,["fumee","plus loin","alentours","horizon"])){let ok=await roll("Perception","SAG",10);if(ok){G.clueSmoke=true;msg("narrator","Tu distingues une fine colonne de fumée qui s'élève entre les arbres, à l'écart du chemin.")}else msg("narrator","Les arbres masquent trop bien les alentours.");return}if(G.clueSmoke&&any(a.t,["suis","suivre","vais voir","vers la fumee","direction de la fumee"])){scene("cabin",true);msg("narrator","Tu suis la fumée jusqu'à une petite cabane rustique. Un vieux fermier travaille près de l'entrée tandis qu'un cheval nain broute tranquillement à côté.");msg("npc","<b>Vieux fermier :</b> « Si vous êtes des vendeurs, j'ai besoin de rien. »");return}if(any(a.t,["continue","route","chemin"])){msg("narrator","Tu peux continuer vers les montagnes, mais quelque chose dans cette clairière mérite peut-être encore ton attention.");return}msg("system","La clairière peut être fouillée, ses baies étudiées, ou les alentours observés.")}
async function cabin(a){if(any(a.t,["qui etes","votre nom","qui es-tu"])){msg("npc","<b>Vieux fermier :</b> « Mon nom n'intéresse pas les vendeurs. »");return}if(a.t.includes("cheval")&&any(a.t,["beau","joli","magnifique","adorable","superbe"])){msg("narrator","Le visage fermé du vieil homme change immédiatement.");msg("npc","<b>Vieux fermier :</b> « Ah ! Enfin quelqu'un qui a des yeux. Regardez-moi cette merveille ! »");G.npcs.farmer=baseNpc("Vieux fermier","secretive");G.npcs.farmer.warmth=3;return}if(any(a.t,["berdesa","chariot","village"])){msg("npc","<b>Vieux fermier :</b> « Il y a un problème à l'est, du côté de Berdésa. Les chariots se font rares dernièrement. »");return}if(a.observe){let ok=await roll("Perspicacité","SAG",13);msg("narrator",ok?"Ses mains et sa posture ne correspondent pas vraiment à celles d'un simple fermier. Il surveille beaucoup plus qu'il ne travaille.":"Tu vois surtout un vieil homme bourru, sa cabane et son petit cheval.");return}msg("npc","<b>Vieux fermier :</b> « Alors ? Vous voulez quelque chose ? »")}
async function act(raw){if(!raw.trim())return;msg("player",raw);let a=analyze(raw);if(G.scene==="gate")await gate(a);else if(G.scene==="outside"){if(any(a.t,["bois","nord","foret"])){scene("forest");msg("narrator","Tu pars vers le nord et entres dans le Bois Tendre avec peu d'informations.")}else msg("narrator","Tu es libre aux abords de Dassom.")}else if(G.scene==="forest")await forest(a);else if(G.scene==="clearing")await clearing(a);else if(G.scene==="cabin")await cabin(a);side()}
function start(){let stats={};ST.forEach(n=>stats[n]=Number($("s_"+n).value)||10);G.char={name:$("name").value.trim()||"Aventurier",race:$("race").value,klass:$("klass").value,stats};$("create").hidden=true;$("game").hidden=false;$("who").textContent=G.char.name;$("sheet").innerHTML=`${G.char.race} • ${G.char.klass} • Niveau 1<br><br>`+ST.map(n=>`${n} ${stats[n]} (${sign(mod(stats[n]))})`).join("<br>");scene("gate");side();msg("narrator","Kayla et Hilam t'attendent devant les portes Nord de Dassom pour te confier une mission liée aux nouveaux jumeaux.");msg("npc","<b>Kayla :</b> « Merci d'être venu. Pose les questions que tu veux. »")}
function init(){ST.forEach((n,i)=>$("stats").insertAdjacentHTML("beforeend",`<label class=stat>${n}<input id=s_${n} type=number min=3 max=20 value=${DEF[i]}></label>`));$("start").onclick=start;$("send").onclick=()=>{let v=$("action").value;$("action").value="";act(v)};$("action").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("send").click()}};$("debugBtn").onclick=()=>{G.debug=!G.debug;$("debugBtn").textContent=`Debug : ${G.debug?"ON":"OFF"}`;$("debug").hidden=!G.debug}}
document.addEventListener("DOMContentLoaded",init);