const $=x=>document.getElementById(x), names=["FOR","DEX","CON","INT","SAG","CHA"], vals=[15,14,13,12,10,8];let S={scene:"gate",trust:0,hostile:0,inv:[],c:null};
names.forEach((n,i)=>$("stats").innerHTML+=`<label class=stat>${n}<input id="${n}" type=number value="${vals[i]}" min=3 max=20></label>`);
const mod=n=>Math.floor((n-10)/2), has=(t,a)=>a.some(x=>t.includes(x));
function say(c,t){$("log").innerHTML+=`<div class="m ${c}">${t}</div>`;$("log").scrollTop=99999}
function world(){$("world").innerHTML=`Confiance PNJ : ${S.trust}<br>Hostilité : ${S.hostile}<br>Inventaire : ${S.inv.join(", ")||"—"}`}
function scene(s){S.scene=s;let d={gate:["Entrée Nord de Dassom","🏰 👩‍🦳 🧑‍🦱 ⚔️"],forest:["Bois Tendre","🌲 🍃 🌳 🐿️"],clearing:["Clairière","🌳 ⚫ 🔵 🔴 🌳"],cabin:["Cabane isolée","🛖 🐴 🔥 🌾"]}[s];$("place").textContent=d[0];$("art").textContent=d[1]}
async function roll(label,ability,dc){return new Promise(ok=>{let b=mod(S.c.st[ability]),o=$("overlay"),d=$("die");$("test").textContent=`${label} • ${ability} ${b>=0?"+":""}${b}`;$("result").textContent="";o.classList.add("on");let q=setInterval(()=>d.textContent=1+Math.floor(Math.random()*20),65);setTimeout(()=>{clearInterval(q);let r=1+Math.floor(Math.random()*20),tot=r+b;d.textContent=r;$("result").textContent=`${r} ${b>=0?"+":""}${b} = ${tot} • DD ${dc} • ${tot>=dc?"RÉUSSITE":"ÉCHEC"}`;setTimeout(()=>{o.classList.remove("on");ok(tot>=dc)},1100)},900)})}
async function act(raw){let t=raw.toLowerCase().trim();if(!t)return;say("p",raw);if(has(t,["idiot","crétin","menace","attaque","frappe","tue"]))S.hostile+=2;if(has(t,["bonjour","merci","magnifique","joli","désolé"]))S.trust++;
if(S.scene==="gate"){if(has(t,["cache","mentez","sincère"])){let x=await roll("Perspicacité","SAG",12);say("n",x?"Kayla est sincèrement inquiète, mais retient une partie de la vérité.":"Tu n'arrives pas à lire ses intentions.");}else if(has(t,["pourquoi","jumeaux","récompense","payer"])){say("npc","<b>Hilam :</b> « Leur sécurité est essentielle. Dassom saura vous récompenser généreusement. »")}else if(has(t,["pars","partons","bois","route","quitte","continue"])){scene("forest");say("n","Vous entrez dans le Bois Tendre. Ton compagnon Neria marche à tes côtés.")}else say("npc","<b>Kayla :</b> « Je t'écoute. Certaines réponses devront cependant attendre. »")}
else if(S.scene==="forest"){if(has(t,["observe","cherche","regarde"])){let x=await roll("Perception","SAG",10);say("n",x?"Tu distingues une fine fumée entre les arbres.":"Rien d'inhabituel ne saute aux yeux.")}else if(has(t,["sépare","seul"])){let x=await roll("Perception","SAG",11);say("n",x?"Tu entends un loup affamé avant son arrivée et peux te préparer.":"Un loup affamé surgit et te surprend !")}else if(has(t,["continue","avance","clairière","chemin"])){scene("clearing");say("n","Le chemin débouche sur une clairière où poussent des baies noires, bleues et rouges.")}else say("n","Ton action est enregistrée. Cette version locale ne sait pas encore improviser toutes ses conséquences.")}
else if(S.scene==="clearing"){if(has(t,["identifier","nature","connais","étudie"])){let x=await roll("Nature","INT",11);say("n",x?"Tu identifies les baies : noire contre la putréfaction, bleue soigne légèrement, rouge est nocive pendant sa digestion.":"Tu n'es pas certain de leurs propriétés.")}else if(has(t,["cueille","récolte","prends"])&&has(t,["rouge","bleue","noire"])){let c=has(t,["rouge"])?"rouge":has(t,["bleue"])?"bleue":"noire";S.inv.push("baie "+c);say("n","Tu récoltes une baie "+c+".")}else if(has(t,["fumée","cabane","aller voir"])){scene("cabin");say("n","La fumée mène à une petite cabane. Un cheval nain broute devant.");say("npc","<b>Fermier :</b> « Des vendeurs ? Non merci. »")}else say("n","Tu peux examiner les baies, chercher la fumée ou tenter toute autre action.")}
else{if(has(t,["cheval"])&&has(t,["beau","joli","magnifique","adorable","superbe"])){S.trust+=3;say("npc","Le fermier s'illumine. <b>« Enfin quelqu'un avec des yeux ! Il s'appelle Pécorin ! »</b>")}else if(has(t,["menace","attaque","frappe","arme"])){let x=await roll("Intimidation","CHA",15);say("npc",x?"« Range ça. Ensuite nous parlerons. »":"Le fermier ne semble pas impressionné. « Mauvaise idée. »")}else if(has(t,["berdésa","berdesa","chariot"])){say("npc","<b>Fermier :</b> « Les chariots se font rares à Berdésa. Si vous avez le temps, allez voir. »")}else if(has(t,["qui es","qui êtes","sage","cache","fermier"])){let x=await roll("Perspicacité","SAG",14);say("npc",x?"« Un fermier qui aime son cheval. Ça ne suffit pas ? » Son regard confirme presque qu'il joue un rôle.":"« Je suis exactement ce que vous voyez. »")}else say("npc",S.hostile>2?"Le fermier suit chacun de tes gestes, méfiant.":"Le fermier t'observe. « Continue, je t'écoute. »")} }world()}
$("start").onclick=()=>{let st={};names.forEach(n=>st[n]=+$(""+n).value);S.c={name:$("name").value||"Aventurier",race:$("race").value,k:$("klass").value,st};$("create").hidden=true;$("game").hidden=false;$("who").textContent=S.c.name;$("sheet").innerHTML=`${S.c.race} • ${S.c.k}<br>`+names.map(n=>`${n} ${st[n]} (${mod(st[n])>=0?"+":""}${mod(st[n])})`).join("<br>");scene("gate");world();say("n","Kayla et Hilam vous attendent devant les portes Nord. Les nouveaux jumeaux doivent apparaître au Lac Rose.");say("npc","<b>Kayla :</b> « Nous comptons sur vous. Posez vos questions si vous en avez. »");say("n","Écris librement ce que ton personnage dit ou tente.")};
$("send").onclick=()=>{let v=$("action").value;$("action").value="";act(v)};$("action").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("send").click()}};